// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: event_registrations.sql

package data

import (
	"context"
)

const getEventIdentityRegistration = `-- name: GetEventIdentityRegistration :one
SELECT
    eon,
    identity,
    identity_prefix,
    sender,
    event_trigger_definition,
    COALESCE(expiration_block_number, 0) AS expiration_block_number,
    tx_hash,
    created_at
FROM event_identity_registration
WHERE eon = $1 AND identity = $2
`

type GetEventIdentityRegistrationParams struct {
	Eon      int64
	Identity []byte
}

func (q *Queries) GetEventIdentityRegistration(ctx context.Context, arg GetEventIdentityRegistrationParams) (EventIdentityRegistration, error) {
	row := q.db.QueryRow(ctx, getEventIdentityRegistration, arg.Eon, arg.Identity)
	var i EventIdentityRegistration
	err := row.Scan(
		&i.Eon,
		&i.Identity,
		&i.IdentityPrefix,
		&i.Sender,
		&i.EventTriggerDefinition,
		&i.ExpirationBlockNumber,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getEventTriggerExpirationBlockNumber = `-- name: GetEventTriggerExpirationBlockNumber :one
SELECT COALESCE(expiration_block_number, 0) FROM event_identity_registration
WHERE eon = $1 AND identity = $2
`

type GetEventTriggerExpirationBlockNumberParams struct {
	Eon      int64
	Identity []byte
}

func (q *Queries) GetEventTriggerExpirationBlockNumber(ctx context.Context, arg GetEventTriggerExpirationBlockNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, getEventTriggerExpirationBlockNumber, arg.Eon, arg.Identity)
	var expiration_block_number int64
	err := row.Scan(&expiration_block_number)
	return expiration_block_number, err
}

const insertEventIdentityRegistration = `-- name: InsertEventIdentityRegistration :exec

INSERT INTO event_identity_registration (
    eon,
    identity,
    identity_prefix,
    sender,
    event_trigger_definition,
    tx_hash
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (eon, identity) DO NOTHING
`

type InsertEventIdentityRegistrationParams struct {
	Eon                    int64
	Identity               []byte
	IdentityPrefix         []byte
	Sender                 string
	EventTriggerDefinition []byte
	TxHash                 []byte
}

// write sql queries here
func (q *Queries) InsertEventIdentityRegistration(ctx context.Context, arg InsertEventIdentityRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertEventIdentityRegistration,
		arg.Eon,
		arg.Identity,
		arg.IdentityPrefix,
		arg.Sender,
		arg.EventTriggerDefinition,
		arg.TxHash,
	)
	return err
}

const updateEventIdentityRegistrationExpirationBlockNumber = `-- name: UpdateEventIdentityRegistrationExpirationBlockNumber :exec
UPDATE event_identity_registration
SET expiration_block_number = $1
WHERE eon = $2 AND identity = $3
`

type UpdateEventIdentityRegistrationExpirationBlockNumberParams struct {
	ExpirationBlockNumber int64
	Eon                   int64
	Identity              []byte
}

func (q *Queries) UpdateEventIdentityRegistrationExpirationBlockNumber(ctx context.Context, arg UpdateEventIdentityRegistrationExpirationBlockNumberParams) error {
	_, err := q.db.Exec(ctx, updateEventIdentityRegistrationExpirationBlockNumber, arg.ExpirationBlockNumber, arg.Eon, arg.Identity)
	return err
}
