// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: event_registrations.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventIdentityRegistration = `-- name: GetEventIdentityRegistration :one
SELECT eon, identity, identity_prefix, eon_key, event_trigger_definition, ttl, tx_hash, created_at FROM event_identity_registration
WHERE eon = $1 AND identity = $2
`

type GetEventIdentityRegistrationParams struct {
	Eon      int64
	Identity []byte
}

func (q *Queries) GetEventIdentityRegistration(ctx context.Context, arg GetEventIdentityRegistrationParams) (EventIdentityRegistration, error) {
	row := q.db.QueryRow(ctx, getEventIdentityRegistration, arg.Eon, arg.Identity)
	var i EventIdentityRegistration
	err := row.Scan(
		&i.Eon,
		&i.Identity,
		&i.IdentityPrefix,
		&i.EonKey,
		&i.EventTriggerDefinition,
		&i.Ttl,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getEventIdentityRegistrationTTL = `-- name: GetEventIdentityRegistrationTTL :one
SELECT ttl FROM event_identity_registration
WHERE eon = $1 AND identity = $2
`

type GetEventIdentityRegistrationTTLParams struct {
	Eon      int64
	Identity []byte
}

func (q *Queries) GetEventIdentityRegistrationTTL(ctx context.Context, arg GetEventIdentityRegistrationTTLParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getEventIdentityRegistrationTTL, arg.Eon, arg.Identity)
	var ttl pgtype.Int8
	err := row.Scan(&ttl)
	return ttl, err
}

const insertEventIdentityRegistration = `-- name: InsertEventIdentityRegistration :exec

INSERT INTO event_identity_registration (
    eon,
    identity,
    identity_prefix,
    eon_key,
    event_trigger_definition,
    ttl,
    tx_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (eon, identity) DO NOTHING
`

type InsertEventIdentityRegistrationParams struct {
	Eon                    int64
	Identity               []byte
	IdentityPrefix         []byte
	EonKey                 []byte
	EventTriggerDefinition []byte
	Ttl                    pgtype.Int8
	TxHash                 []byte
}

// write sql queries here
func (q *Queries) InsertEventIdentityRegistration(ctx context.Context, arg InsertEventIdentityRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertEventIdentityRegistration,
		arg.Eon,
		arg.Identity,
		arg.IdentityPrefix,
		arg.EonKey,
		arg.EventTriggerDefinition,
		arg.Ttl,
		arg.TxHash,
	)
	return err
}
