// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DecryptionKey struct {
	Eon           int64
	EpochID       []byte
	DecryptionKey []byte
}

type EventIdentityRegistration struct {
	Eon                    int64
	Identity               []byte
	IdentityPrefix         []byte
	Sender                 string
	EventTriggerDefinition []byte
	ExpirationBlockNumber  int64
	TxHash                 []byte
	CreatedAt              pgtype.Timestamp
}
